name: Elasticsearch Visualization

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Iniciar Elasticsearch sin seguridad
      run: |
        docker run -d --name elasticsearch -p 9200:9200 \
          -e "discovery.type=single-node" \
          -e "xpack.security.enabled=false" \
          -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
          docker.elastic.co/elasticsearch/elasticsearch:8.13.0

    - name: Esperar que Elasticsearch esté listo
      run: |
        echo "Esperando a Elasticsearch..."
        for i in {1..30}; do
          if curl -s http://localhost:9200 >/dev/null; then
            echo "Elasticsearch está listo!"
            break
          fi
          sleep 2
        done

    - name: Instalar dependencias
      run: |
        pip install elasticsearch pandas matplotlib seaborn

    - name: Ejecutar script
      run: python3 script.py
