name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install pandas matplotlib

      - name: Ejecutar script de Python
        run: python script.py

      - name: Crear archivo .nojekyll
        run: touch .nojekyll

      - name: Subir archivos como artefacto
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Crear la rama gh-pages si no existe
        run: |
          git fetch origin
          if ! git show-ref --quiet refs/remotes/origin/gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
            echo "# GitHub Pages" > index.html
            git add index.html
            git commit -m "Crear rama gh-pages"
            git push origin gh-pages
          else
            echo "La rama gh-pages ya existe."
          fi

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
