name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install pandas matplotlib

      - name: Ejecutar script de Python
        run: python script.py

      - name: Crear archivo .nojekyll
        run: touch .nojekyll

      - name: Subir artefactos para Pages
        uses: actions/upload-artifact@v3
        with:
          name: pages-artifact
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar a GitHub Pages
        uses: actions/deploy-pages@v2
