name: Elasticsearch Viz

on:
  push:
    branches:
      - main

jobs:
  elasticsearch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Detener y eliminar contenedor Elasticsearch si existe
      run: |
        docker ps -q --filter "name=elasticsearch" | xargs -r docker stop | xargs -r docker rm

    - name: Pull Elasticsearch image
      run: |
        docker pull docker.elastic.co/elasticsearch/elasticsearch:8.13.0

    - name: Run Elasticsearch container
      run: |
        docker run -d --name elasticsearch -p 9301:9200 \
          -e "discovery.type=single-node" \
          -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
          docker.elastic.co/elasticsearch/elasticsearch:8.13.0

    - name: Wait for Elasticsearch to be ready
      run: |
        until curl -s http://localhost:9301/_cluster/health?pretty | grep -q '"status" : "green"'; do
          echo "Esperando Elasticsearch a que esté listo...";
          sleep 5;
        done

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python script.py
