name: Elasticsearch Viz

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
        ports:
          - 9200:9200
        options: >-
          --health-cmd="curl --silent --fail http://localhost:9200/_cluster/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install elasticsearch pandas matplotlib seaborn

      - name: Wait for Elasticsearch to be ready
        run: |
          echo "⏳ Esperando a que Elasticsearch esté disponible..."
          for i in {1..30}; do
            if curl --silent --fail http://localhost:9200; then
              echo "✅ Elasticsearch está listo."
              break
            fi
            echo "🔁 Intento $i: Elasticsearch aún no responde..."
            sleep 2
          done
          if [ $i -eq 30 ]; then
            echo "❌ No se pudo conectar a Elasticsearch."
            exit 1
          fi

      - name: Run the script
        run: python3 script.py
