name: Elasticsearch Data Visualization

on:
  push:
    branches:
      - main

jobs:
  elasticsearch-viz:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
        ports:
          - 9202:9200  # Cambié el puerto a 9202 para evitar conflicto
        options: >-
          --env discovery.type=single-node
          --env "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    steps:
    # Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Configurar Docker para Elasticsearch
    - name: Configurar Elasticsearch
      run: |
        docker pull docker.elastic.co/elasticsearch/elasticsearch:8.13.0
        docker run -d --name elasticsearch -p 9202:9200 \
          -e "discovery.type=single-node" \
          -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
          docker.elastic.co/elasticsearch/elasticsearch:8.13.0

    # Esperar que Elasticsearch esté listo
    - name: Esperar que Elasticsearch esté listo
      run: |
        until curl -s http://localhost:9202 > /dev/null; do  # Cambié el puerto a 9202
          echo "Esperando Elasticsearch..."
          sleep 5
        done

    # Verificar que Elasticsearch esté funcionando
    - name: Comprobar Elasticsearch
      run: curl -X GET "localhost:9202/"  # Cambié el puerto a 9202

    # Instalar dependencias necesarias
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Ejecutar el script de Python
    - name: Run python script.py
      run: python script.py
