name: Elasticsearch + Python + GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Iniciar Elasticsearch con Docker
        run: |
          docker pull docker.elastic.co/elasticsearch/elasticsearch:8.13.0
          docker run -d --name elasticsearch \
            -p 9200:9200 \
            -e "discovery.type=single-node" \
            -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
            docker.elastic.co/elasticsearch/elasticsearch:8.13.0

      - name: Esperar a que Elasticsearch esté listo
        run: |
          echo "Esperando a Elasticsearch..."
          for i in {1..60}; do
            status=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:9200)
            if [ "$status" = "200" ]; then
              echo "Elasticsearch está listo (HTTP 200)."
              break
            fi
            echo "Esperando ($i)..."
            sleep 5
          done

      - name: Instalar dependencias de Python
        run: |
          python3 -m pip install --upgrade pip
          pip install elasticsearch pandas matplotlib seaborn

      - name: Ejecutar script Python
        run: python3 script.py

      - name: Subir cambios a GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Actualizar visualización"
          git push
