name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install pandas matplotlib

      - name: Ejecutar script de Python
        run: python script.py

      - name: Crear archivo .nojekyll
        run: touch .nojekyll

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Subir a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Cambia esto a la ruta donde están tus archivos HTML y gráficos
